### ISSUE TITLE
[RESOLVED] Location key to use for src/main.js? 

### ISSUE THREAD

**Issue by Pixel-Door** [refact0r/startpage#1]
Resolved by commenting out name and location variables (Lines 7 & 8), not a permanent solution but good enough for me.

To be frank I'm sure I'm just doing something wrong but I'd appreciate some response.
I've scrolled through the openweather api guide, as everytime I put in a input for the `location` variable, I get the error:

```pixeldoor@fedora ~/startpage (master)> npm run build

> startpage@1.0.0 build
> rollup -c


src/main.js → public/build/bundle.js...
[!] (plugin commonjs) SyntaxError: Unexpected token (8:2) in /home/pixeldoor/startpage/src/main.js
src/main.js (8:2)
 6:     // CHANGE THESE VARIABLES
 7:     name: 'Pixeldoor'
 8:     location: 'Austin'
        ^
 9:
10:     apiKey: 'd23d00148164134a876863a10896e725'
SyntaxError: Unexpected token (8:2) in /home/pixeldoor/startpage/src/main.js
    at Object.pp$4.raise (/home/pixeldoor/startpage/node_modules/rollup/dist/shared/rollup.js:15685:13)
    at Object.pp.unexpected (/home/pixeldoor/startpage/node_modules/rollup/dist/shared/rollup.js:13377:8)
    at Object.pp.expect (/home/pixeldoor/startpage/node_modules/rollup/dist/shared/rollup.js:13371:26)
    at Object.pp$3.parseObj (/home/pixeldoor/startpage/node_modules/rollup/dist/shared/rollup.js:15321:12)
    at Object.pp$3.parseExprAtom (/home/pixeldoor/startpage/node_modules/rollup/dist/shared/rollup.js:15060:17)
    at Object.pp$3.parseExprSubscripts (/home/pixeldoor/startpage/node_modules/rollup/dist/shared/rollup.js:14887:19)
    at Object.pp$3.parseMaybeUnary (/home/pixeldoor/startpage/node_modules/rollup/dist/shared/rollup.js:14864:17)
    at Object.parseMaybeUnary (/home/pixeldoor/startpage/node_modules/rollup/dist/shared/rollup.js:19630:29)
    at Object.pp$3.parseExprOps (/home/pixeldoor/startpage/node_modules/rollup/dist/shared/rollup.js:14799:19)
    at Object.pp$3.parseMaybeConditional (/home/pixeldoor/startpage/node_modules/rollup/dist/shared/rollup.js:14782:19)
```
Cheers! -Pixel

**Comment by refact0r** [comment]
I'm pretty sure you need a comma after each string value like
```
name: 'Pixeldoor',
location: 'Austin',
```
